api = "0.2"

[buildpack]
id = "google.php.composer"
version = "0.9.0"
name = "PHP - Composer"

[[stacks]]
id = "google"

[[stacks]]
id = "google.php72"

[[stacks]]
id = "google.php73"

[[stacks]]
id = "google.php74"
