api = "0.5"

[buildpack]
id = "google.ruby.functions-framework"
version = "0.9.1"
name = "Ruby - Functions Framework"

[[stacks]]
id = "google"

[[stacks]]
id = "google.ruby26"

[[stacks]]
id = "google.ruby27"

[[stacks]]
id = "google.ruby30"
