description = "Builder for the GAE PHP 7.4 runtime"

[[buildpacks]]
  id = "google.php.composer"
  uri = "composer.tgz"

[[buildpacks]]
  id = "google.php.composer-gcp-build"
  uri = "composer_gcp_build.tgz"

[[buildpacks]]
  id = "google.php.appengine"
  uri = "appengine.tgz"

[[order]]
  [[order.group]]
    id = "google.php.composer-gcp-build"
    optional = true

  [[order.group]]
    id = "google.php.composer"
    optional = true

  [[order.group]]
    id = "google.php.appengine"

[stack]
  id = "google.php73"
  build-image = "gcr.io/gae-runtimes/buildpacks/php73/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/php73/run"

[lifecycle]
  version = "0.7.2"
