api = "0.2"

[buildpack]
id = "google.python.functions-framework"
version = "0.9.1"
name = "Python - Functions Framework"

[[stacks]]
id = "google"

[[stacks]]
id = "google.python37"

[[stacks]]
id = "google.python38"

[[stacks]]
id = "google.python39"
