api = "0.2"

[buildpack]
id = "google.python.pip"
version = "0.9.2"
name = "Python - pip"

[[stacks]]
id = "google"

[[stacks]]
id = "google.python37"

[[stacks]]
id = "google.python38"

[[stacks]]
id = "google.python39"
