description = "Builder for the GAE Go 1.15 runtime"

[[buildpacks]]
  id = "google.go.appengine"
  uri = "appengine.tgz"

[[buildpacks]]
  id = "google.go.build"
  uri = "build.tgz"

[[buildpacks]]
  id = "google.go.appengine_gopath"
  uri = "appengine_gopath.tgz"

[[buildpacks]]
  id = "google.go.gomod"
  uri = "gomod.tgz"

[[buildpacks]]
  id = "google.go.appengine_gomod"
  uri = "appengine_gomod.tgz"

[[order]]

  [[order.group]]
    id = "google.go.appengine_gomod"
    optional = true

  [[order.group]]
    id = "google.go.gomod"

  [[order.group]]
    id = "google.go.build"

  [[order.group]]
    id = "google.go.appengine"

[[order]]

  [[order.group]]
    id = "google.go.appengine_gopath"

  [[order.group]]
    id = "google.go.build"

  [[order.group]]
    id = "google.go.appengine"


[stack]
  id = "google.go115"
  build-image = "gcr.io/gae-runtimes/buildpacks/go115/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/go115/run"

[lifecycle]
  version = "0.8.1"
