api = "0.2"

[buildpack]
id = "google.go.appengine_gopath"
version = "0.9.0"
name = "Go - App Engine GOPATH"

[[stacks]]
id = "google.go112"

[[stacks]]
id = "google.go113"

[[stacks]]
id = "google.go114"
