api = "0.5"

[buildpack]
id = "google.go.appengine_gopath"
version = "0.9.0"
name = "Go - App Engine GOPATH"

[[stacks]]
id = "google.go111"

[[stacks]]
id = "google.go112"

[[stacks]]
id = "google.go113"

[[stacks]]
id = "google.go116"

[[stacks]]
id = "google.go114"

[[stacks]]
id = "google.go115"

[[stacks]]
id = "google.go116"