description = "Unified builder for the PHP runtime"

[[buildpacks]]
  id = "google.config.entrypoint"
  uri = "entrypoint.tgz"

[[buildpacks]]
  id = "google.php.composer"
  uri = "composer.tgz"

[[buildpacks]]
  id = "google.php.composer-install"
  uri = "composer_install.tgz"

[[buildpacks]]
  id = "google.php.composer-gcp-build"
  uri = "composer_gcp_build.tgz"

[[buildpacks]]
  id = "google.php.appengine"
  uri = "appengine.tgz"

[[buildpacks]]
  id = "google.php.runtime"
  uri = "runtime.tgz"

[[buildpacks]]
  id = "google.php.webconfig"
  uri = "webconfig.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[buildpacks]]
  id = "google.utils.nginx"
  uri = "nginx.tgz"

[[buildpacks]]
  id = "google.php.functions-framework"
  uri = "functions_framework.tgz"

[[buildpacks]]
  id = "google.php.cloudfunctions"
  uri = "cloudfunctions.tgz"

[[buildpacks]]
  id = "google.utils.archive-source"
  uri = "archive_source.tgz"

# PHP applications (gcf)
[[order]]
  [[order.group]]
    id = "google.php.runtime"

  [[order.group]]
    id = "google.utils.archive-source"

  [[order.group]]
    id = "google.php.composer-install"
    optional = true

  [[order.group]]
    id = "google.php.composer-gcp-build"
    optional = true

  [[order.group]]
    id = "google.php.composer"
    optional = true

  [[order.group]]
    id = "google.php.functions-framework"

  [[order.group]]
    id = "google.php.cloudfunctions"

  [[order.group]]
    id = "google.utils.label"

# PHP applications (gae)
[[order]]
  [[order.group]]
    id = "google.php.runtime"

  [[order.group]]
    id = "google.php.composer-install"
    optional = true

  [[order.group]]
    id = "google.php.composer-gcp-build"
    optional = true

  [[order.group]]
    id = "google.php.composer"
    optional = true

  [[order.group]]
    id = "google.php.appengine"

  [[order.group]]
    id = "google.utils.label"

# PHP applications (gcp and cloud-run)
[[order]]
  [[order.group]]
    id = "google.php.runtime"

  [[order.group]]
    id = "google.utils.nginx"

  [[order.group]]
    id = "google.php.composer-install"
    optional = true

  [[order.group]]
    id = "google.php.composer"
    optional = true

  [[order.group]]
    id = "google.utils.label"

  [[order.group]]
    id = "google.php.webconfig"

[stack]
  id = "google.gae.18"
  build-image = "gcr.io/gae-runtimes/buildpacks/stacks/google-gae-18/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/stacks/google-gae-18/run"

[lifecycle]
  version = "0.13.3"
