description = "Builder for the GAE Node.js 12 runtime"

[[buildpacks]]
  id = "google.nodejs.npm"
  uri = "npm.tgz"

[[buildpacks]]
  id = "google.nodejs.npm-gcp-build"
  uri = "npm_gcp_build.tgz"

[[buildpacks]]
  id = "google.nodejs.yarn"
  uri = "yarn.tgz"

[[buildpacks]]
  id = "google.nodejs.yarn-gcp-build"
  uri = "yarn_gcp_build.tgz"

[[buildpacks]]
  id = "google.nodejs.appengine"
  uri = "appengine.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]
  [[order.group]]
    id = "google.nodejs.yarn-gcp-build"
    optional = true

  [[order.group]]
    id = "google.nodejs.yarn"

  [[order.group]]
    id = "google.nodejs.appengine"

  [[order.group]]
    id = "google.utils.label"

[[order]]
  [[order.group]]
    id = "google.nodejs.npm-gcp-build"
    optional = true

  [[order.group]]
    id = "google.nodejs.npm"
    optional = true

  [[order.group]]
    id = "google.nodejs.appengine"

  [[order.group]]
    id = "google.utils.label"

[stack]
  id = "google.nodejs12"
  build-image = "gcr.io/gae-runtimes/buildpacks/nodejs12/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/nodejs12/run"

[lifecycle]
  version = "0.9.1"
