description = "Builder for the GAE Go 1.11 runtime"

[[buildpacks]]
  id = "google.go.appengine"
  uri = "appengine.tgz"

[[buildpacks]]
  id = "google.go.build"
  uri = "build.tgz"

[[buildpacks]]
  id = "google.go.appengine_gopath"
  uri = "appengine_gopath.tgz"

[[buildpacks]]
  id = "google.go.gomod"
  uri = "gomod.tgz"

[[buildpacks]]
  id = "google.go.appengine_gomod"
  uri = "appengine_gomod.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]

  [[order.group]]
    id = "google.go.appengine_gomod"
    optional = true

  [[order.group]]
    id = "google.go.gomod"

  [[order.group]]
    id = "google.go.build"

  [[order.group]]
    id = "google.go.appengine"

  [[order.group]]
    id = "google.utils.label"

[[order]]

  [[order.group]]
    id = "google.go.appengine_gopath"

  [[order.group]]
    id = "google.go.build"

  [[order.group]]
    id = "google.go.appengine"

  [[order.group]]
    id = "google.utils.label"


[stack]
  id = "google.go111"
  build-image = "gcr.io/gae-runtimes/buildpacks/go111/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/go111/run"

[lifecycle]
  version = "0.13.1"
