api = "0.5"

[buildpack]
id = "google.nodejs.yarn-gcp-build"
version = "0.9.0"
name = "Node.js - Yarn gcp-build"

[[stacks]]
id = "google.nodejs8"

[[stacks]]
id = "google.nodejs10"

[[stacks]]
id = "google.nodejs12"

[[stacks]]
id = "google.nodejs14"

[[stacks]]
id = "google.nodejs16"