description = "Builder for the Java runtime"

[[buildpacks]]
  id = "google.java.appengine"
  uri = "appengine.tgz"

[[buildpacks]]
  id = "google.utils.archive-source"
  uri = "archive_source.tgz"

[[buildpacks]]
  id = "google.config.entrypoint"
  uri = "entrypoint.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[buildpacks]]
  id = "google.java.entrypoint"
  uri = "java/entrypoint.tgz"

[[buildpacks]]
  id = "google.java.exploded-jar"
  uri = "java/exploded_jar.tgz"

[[buildpacks]]
  id = "google.java.functions-framework"
  uri = "java/functions_framework.tgz"

[[buildpacks]]
  id = "google.java.gradle"
  uri = "java/gradle.tgz"

[[buildpacks]]
  id = "google.java.maven"
  uri = "java/maven.tgz"

[[buildpacks]]
  id = "google.java.runtime"
  uri = "java/runtime.tgz"

[[buildpacks]]
  id = "google.java.clear_source"
  uri = "java/clear_source.tgz"

# The GCF order group.
# We'll use google.java.maven to compile the function code if there is a pom.xml.
# In that case google.java.functions-framework will inspect the pom.xml to
# determine what should be in the classpath of the final function.
[[order]]
  [[order.group]]
    id = "google.java.runtime"

  [[order.group]]
    id = "google.utils.archive-source"

  [[order.group]]
    id = "google.java.maven"

  [[order.group]]
    id = "google.java.functions-framework"

  [[order.group]]
    id = "google.utils.label"

# We'll use google.java.gradle to compile the function code if there is a build.gradle.
# In that case google.java.functions-framework will inspect the build.gradle to
# determine what should be in the classpath of the final function. Since
# google.java.gradle is optional, google.java.functions-framework will also run
# if there is neither a pom.xml nor a build.gradle. In that case, it expects
# there is an already-compiled jar file and that's what it will put in the
# classpath.
[[order]]
  [[order.group]]
    id = "google.java.runtime"

  [[order.group]]
    id = "google.utils.archive-source"

  [[order.group]]
    id = "google.java.gradle"
    optional = true

  [[order.group]]
    id = "google.java.functions-framework"

  [[order.group]]
    id = "google.utils.label"

# The GCP order group.
# Functions have separate groups because entrypoint not supported.
[[order]]
  [[order.group]]
    id = "google.java.runtime"

  [[order.group]]
    id = "google.java.maven"

  [[order.group]]
    id = "google.java.functions-framework"

  [[order.group]]
    id = "google.java.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

[[order]]
  [[order.group]]
    id = "google.java.runtime"

  [[order.group]]
    id = "google.java.gradle"
    optional = true

  [[order.group]]
    id = "google.java.functions-framework"

  [[order.group]]
    id = "google.java.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

# Exploded Jars
[[order]]
  [[order.group]]
    id = "google.java.runtime"

  [[order.group]]
    id = "google.java.exploded-jar"

  [[order.group]]
    id = "google.utils.label"

# Maven applications.
[[order]]
  [[order.group]]
    id = "google.java.runtime"

  [[order.group]]
    id = "google.java.maven"

  [[order.group]]
    id = "google.config.entrypoint"

  [[order.group]]
    id = "google.java.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

[[order]]
  [[order.group]]
    id = "google.java.runtime"

  [[order.group]]
    id = "google.java.maven"

  [[order.group]]
    id = "google.java.entrypoint"

  [[order.group]]
    id = "google.java.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

# Gradle & Jar-based applications.
[[order]]
  [[order.group]]
    id = "google.java.runtime"

  [[order.group]]
    id = "google.java.gradle"
    optional = true

  [[order.group]]
    id = "google.config.entrypoint"

  [[order.group]]
    id = "google.java.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

[[order]]
  [[order.group]]
    id = "google.java.runtime"

  [[order.group]]
    id = "google.java.gradle"
    optional = true

  [[order.group]]
    id = "google.java.entrypoint"

  [[order.group]]
    id = "google.java.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"


# Currently built with //builders/gcp/base/stack/stack:build.
[stack]
  id = "google.gae.18"
  build-image = "gcr.io/gae-runtimes/buildpacks/stacks/google-gae-18/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/stacks/google-gae-18/run"

[lifecycle]
  version = "0.15.1"
