description = "Builder for the GCF Ruby 2.6 runtime"

[[buildpacks]]
  id = "google.ruby.bundle"
  uri = "bundle.tgz"

[[buildpacks]]
  id = "google.ruby.functions-framework"
  uri = "functions_framework.tgz"

[[buildpacks]]
  id = "google.utils.archive-source"
  uri = "archive_source.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]

  [[order.group]]
    id = "google.utils.archive-source"

  [[order.group]]
    id = "google.ruby.bundle"

  [[order.group]]
    id = "google.ruby.functions-framework"

  [[order.group]]
    id = "google.utils.label"

[stack]
  id = "google.ruby27"
  build-image = "gcr.io/gae-runtimes/buildpacks/ruby27/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/ruby27/run"

[lifecycle]
  version = "0.9.2"
