api = "0.5"

[buildpack]
id = "google.ruby.appengine_validation"
version = "0.9.0"
name = "Ruby - App Engine Validation"

[[stacks]]
id = "google.ruby25"

[[stacks]]
id = "google.ruby26"

[[stacks]]
id = "google.ruby27"
