api = "0.2"

[buildpack]
id = "google.go.functions-framework"
version = "0.9.0"
name = "Go - Functions Framework"

[[stacks]]
id = "google"

[[stacks]]
id = "google.go113"

[[stacks]]
id = "google.go114"
