api = "0.5"

[buildpack]
id = "google.go.functions-framework"
version = "0.9.4"
name = "Go - Functions Framework"

[[stacks]]
id = "google"

[[stacks]]
id = "google.go111"

[[stacks]]
id = "google.go112"

[[stacks]]
id = "google.go113"

[[stacks]]
id = "google.go116"

[[stacks]]
id = "google.go114"

[[stacks]]
id = "google.go115"

[[stacks]]
id = "google.go116"
