description = "Builder for the GAE Python 3.9 runtime"

[[buildpacks]]
  id = "google.python.webserver"
  uri = "webserver.tgz"

[[buildpacks]]
  id = "google.python.pip"
  uri = "pip.tgz"

[[buildpacks]]
  id = "google.python.appengine"
  uri = "appengine.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]
  [[order.group]]
    id = "google.python.webserver"
    optional = true

  [[order.group]]
    id = "google.python.pip"
    optional = true

  [[order.group]]
    id = "google.python.appengine"

  [[order.group]]
    id = "google.utils.label"

[stack]
  id = "google.python39"
  build-image = "gcr.io/gae-runtimes/buildpacks/python39/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/python39/run"

[lifecycle]
  version = "0.15.1"
