description = "Builder for the GAE Java 11 runtime"

[[buildpacks]]
  id = "google.java.appengine"
  uri = "appengine.tgz"

[[buildpacks]]
  id = "google.java.clear_source"
  uri = "clear_source.tgz"

[[buildpacks]]
  id = "google.java.gradle"
  uri = "gradle.tgz"

[[buildpacks]]
  id = "google.java.maven"
  uri = "maven.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]
  [[order.group]]
    id = "google.java.maven"

  [[order.group]]
    id = "google.java.appengine"

  [[order.group]]
    id = "google.java.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

[[order]]
  [[order.group]]
    id = "google.java.gradle"
    optional = true

  [[order.group]]
    id = "google.java.appengine"

  [[order.group]]
    id = "google.java.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

[stack]
  id = "google.java11"
  build-image = "gcr.io/gae-runtimes/buildpacks/java11/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/java11/run"

[lifecycle]
  version = "0.11.1"
