api = "0.2"

[buildpack]
id = "google.utils.archive-source"
version = "0.0.1"
name = "Utils - Archive Source"

[[stacks]]
id = "google.dotnet3"

[[stacks]]
id = "google.go113"

[[stacks]]
id = "google.java11"

[[stacks]]
id = "google.nodejs10"

[[stacks]]
id = "google.nodejs12"

[[stacks]]
id = "google.php74"

[[stacks]]
id = "google.python38"

[[stacks]]
id = "google.python39"

[[stacks]]
id = "google.ruby26"